# User Churn Prediction

In [1]:
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('churn.all')

### 0.0: Understand the Data.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
state                            5000 non-null object
account_length                   5000 non-null int64
area_code                        5000 non-null int64
phone_number                     5000 non-null object
intl_plan                        5000 non-null object
voice_mail_plan                  5000 non-null object
number_vmail_messages            5000 non-null int64
total_day_minutes                5000 non-null float64
total_day_calls                  5000 non-null int64
total_day_charge                 5000 non-null float64
total_eve_minutes                5000 non-null float64
total_eve_calls                  5000 non-null int64
total_eve_charge                 5000 non-null float64
total_night_minutes              5000 non-null float64
total_night_calls                5000 non-null int64
total_night_charge               5000 non-null float64
total_intl_minutes               5000 non-null float64
total_intl_calls                 5000 non-null int64
total_intl_charge                5000 non-null float64
number_customer_service_calls    5000 non-null int64
churned                          5000 non-null object
dtypes: float64(8), int64(8), object(5)
memory usage: 820.4+ KB

In [12]:
df.sample(5)

,state,account_length,area_code,phone_number,intl_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churned
2595,AL,25,408,337-4600,no,no,0,264.9,80,45.03,281.2,66,23.90,166.1,80,7.47,8.4,4,2.27,1,True.
1727,MS,105,415,343-9654,no,no,0,101.4,48,17.24,159.1,119,13.52,259.2,53,11.66,12.2,2,3.29,1,False.
1175,IA,134,415,373-7037,no,yes,32,216.8,78,36.86,102.2,111,8.69,174.0,83,7.83,8.6,2,2.32,0,False.
2586,MN,53,415,401-9420,no,no,0,164.1,106,27.90,206.0,56,17.51,194.7,124,8.76,11.4,2,3.08,1,False.
929,HI,24,415,343-2077,no,no,0,241.9,104,41.12,145.2,112,12.34,214.5,105,9.65,6.6,5,1.78,1,False.